export const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST';
export const AUTHORIZE_RECEIVE = 'AUTHORIZE_RECEIVE';
export const AUTHORIZE_FAILURE = 'AUTHORIZE_FAILURE';
export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
