export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE'
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE'

export const PRODUCT_RECEIVE = 'PRODUCT_RECEIVE'
export const SITEMAP_RECEIVE = 'SITEMAP_RECEIVE'
export const CATEGORIES_RECEIVE = 'CATEGORIES_RECEIVE'

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
