export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE'
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE'

export const CATEGORIES_SELECT = 'CATEGORIES_SELECT'
export const CATEGORIES_DESELECT = 'CATEGORIES_DESELECT'

export const PRODUCT_CATEGORIES_RECEIVE = 'PRODUCT_CATEGORIES_RECEIVE'
