export const ORDERS_REQUEST = 'ORDERS_REQUEST'
export const ORDERS_RECEIVE = 'ORDERS_RECEIVE'
export const ORDERS_FAILURE = 'ORDERS_FAILURE'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_RECEIVE = 'ORDER_DETAIL_RECEIVE'
export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE'

export const ORDERS_MORE_REQUEST = 'ORDERS_MORE_REQUEST'
export const ORDERS_MORE_RECEIVE = 'ORDERS_MORE_RECEIVE'

export const ORDERS_SET_FILTER = 'ORDERS_SET_FILTER'

export const ORDERS_SELECT = 'ORDERS_SELECT'
export const ORDERS_DESELECT = 'ORDERS_DESELECT'
export const ORDERS_SELECT_ALL = 'ORDERS_SELECT_ALL'
export const ORDERS_DESELECT_ALL = 'ORDERS_DESELECT_ALL'

export const ORDERS_BULK_UPDATE_REQUEST = 'ORDERS_BULK_UPDATE_REQUEST'
export const ORDERS_BULK_UPDATE_SUCCESS = 'ORDERS_BULK_UPDATE_SUCCESS'
export const ORDERS_BULK_UPDATE_FAILURE = 'ORDERS_BULK_UPDATE_FAILURE'

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST'
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS'
export const ORDER_UPDATE_FAILURE = 'ORDER_UPDATE_FAILURE'

export const ORDER_CHECKOUT_REQUEST = 'ORDER_CHECKOUT_REQUEST'
export const ORDER_CHECKOUT_RECEIVE = 'ORDER_CHECKOUT_RECEIVE'
export const ORDER_CHECKOUT_FAILURE = 'ORDER_CHECKOUT_FAILURE'

export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
