export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_RECEIVE = 'PRODUCT_DETAIL_RECEIVE';
export const PRODUCT_DETAIL_FAILURE = 'PRODUCT_DETAIL_FAILURE';
export const PRODUCT_DETAIL_ERASE = 'PRODUCT_DETAIL_ERASE';

export const PRODUCTS_MORE_REQUEST = 'PRODUCTS_MORE_REQUEST';
export const PRODUCTS_MORE_RECEIVE = 'PRODUCTS_MORE_RECEIVE';

export const PRODUCTS_SET_FILTER = 'PRODUCTS_SET_FILTER';

export const PRODUCTS_SELECT = 'PRODUCTS_SELECT';
export const PRODUCTS_DESELECT = 'PRODUCTS_DESELECT';
export const PRODUCTS_SELECT_ALL = 'PRODUCTS_SELECT_ALL';
export const PRODUCTS_DESELECT_ALL = 'PRODUCTS_DESELECT_ALL';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILURE = 'PRODUCT_UPDATE_FAILURE';

export const PRODUCT_OPTIONS_RECEIVE = 'PRODUCT_OPTIONS_RECEIVE';
export const PRODUCT_VARIANTS_RECEIVE = 'PRODUCT_VARIANTS_RECEIVE';
export const PRODUCT_IMAGES_RECEIVE = 'PRODUCT_IMAGES_RECEIVE';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_SET_CATEGORY_SUCCESS = 'PRODUCT_SET_CATEGORY_SUCCESS';

export const PRODUCT_IMAGES_UPLOAD_START = 'PRODUCT_IMAGES_UPLOAD_START';
export const PRODUCT_IMAGES_UPLOAD_END = 'PRODUCT_IMAGES_UPLOAD_END';
