export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const UNSELECT_PRODUCT = 'SELECT_PRODUCT'
export const SELECT_ALL_PRODUCT = 'SELECT_PRODUCT'
