export const GROUPS_REQUEST = 'GROUPS_REQUEST'
export const GROUPS_RECEIVE = 'GROUPS_RECEIVE'
export const GROUPS_FAILURE = 'GROUPS_FAILURE'

export const GROUPS_SELECT = 'GROUPS_SELECT'
export const GROUPS_DESELECT = 'GROUPS_DESELECT'

export const GROUP_UPDATE_REQUEST = 'GROUP_UPDATE_REQUEST'
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS'
export const GROUP_UPDATE_FAILURE = 'GROUP_UPDATE_FAILURE'

export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS'
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS'
