export const ACCOUNT_REQUEST = 'ACCOUNT_REQUEST'
export const ACCOUNT_RECEIVE = 'ACCOUNT_RECEIVE'

export const SERVICES_REQUEST = 'SERVICES_REQUEST'
export const SERVICES_RECEIVE = 'SERVICES_RECEIVE'

export const SERVICE_REQUEST = 'SERVICE_REQUEST'
export const SERVICE_RECEIVE = 'SERVICE_RECEIVE'

export const SERVICE_ENABLE_REQUEST = 'SERVICE_ENABLE_REQUEST'
export const SERVICE_ENABLE_RECEIVE = 'SERVICE_ENABLE_RECEIVE'

export const SERVICE_SETTINGS_REQUEST = 'SERVICE_SETTINGS_REQUEST'
export const SERVICE_SETTINGS_RECEIVE = 'SERVICE_SETTINGS_RECEIVE'

export const SERVICE_LOGS_REQUEST = 'SERVICE_LOGS_REQUEST'
export const SERVICE_LOGS_RECEIVE = 'SERVICE_LOGS_RECEIVE'
