export const ACCOUNT_REQUEST = 'ACCOUNT_REQUEST'
export const ACCOUNT_RECEIVE = 'ACCOUNT_RECEIVE'

export const SERVICES_REQUEST = 'SERVICES_REQUEST'
export const SERVICES_RECEIVE = 'SERVICES_RECEIVE'
