export const FILES_REQUEST = 'FILES_REQUEST';
export const FILES_RECEIVE = 'FILES_RECEIVE';

export const FILES_UPLOAD_START = 'FILES_UPLOAD_START';
export const FILES_UPLOAD_END = 'FILES_UPLOAD_END';
