export const CUSTOMERS_REQUEST = 'CUSTOMERS_REQUEST'
export const CUSTOMERS_RECEIVE = 'CUSTOMERS_RECEIVE'
export const CUSTOMERS_FAILURE = 'CUSTOMERS_FAILURE'

export const CUSTOMERS_DETAIL_REQUEST = 'CUSTOMERS_DETAIL_REQUEST'
export const CUSTOMERS_DETAIL_RECEIVE = 'CUSTOMERS_DETAIL_RECEIVE'
export const CUSTOMERS_DETAIL_FAILURE = 'CUSTOMERS_DETAIL_FAILURE'

export const CUSTOMERS_MORE_REQUEST = 'CUSTOMERS_MORE_REQUEST'
export const CUSTOMERS_MORE_RECEIVE = 'CUSTOMERS_MORE_RECEIVE'

export const CUSTOMERS_FILTER_SET_SEARCH = 'CUSTOMERS_FILTER_SET_SEARCH'

export const CUSTOMERS_SELECT = 'CUSTOMERS_SELECT'
export const CUSTOMERS_DESELECT = 'CUSTOMERS_DESELECT'
export const CUSTOMERS_SELECT_ALL = 'CUSTOMERS_SELECT_ALL'
export const CUSTOMERS_DESELECT_ALL = 'CUSTOMERS_DESELECT_ALL'

export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_SET_GROUP_SUCCESS = 'CUSTOMER_SET_GROUP_SUCCESS'
