export const CUSTOMERS_REQUEST = 'CUSTOMERS_REQUEST'
export const CUSTOMERS_RECEIVE = 'CUSTOMERS_RECEIVE'
export const CUSTOMERS_FAILURE = 'CUSTOMERS_FAILURE'

// export const CUSTOMER_EDIT_REQUEST = 'CUSTOMER_EDIT_REQUEST'
// export const CUSTOMER_EDIT_RECEIVE = 'CUSTOMER_EDIT_RECEIVE'
// export const CUSTOMER_EDIT_FAILURE = 'CUSTOMER_EDIT_FAILURE'
// export const CUSTOMER_EDIT_ERASE = 'CUSTOMER_EDIT_ERASE'

export const CUSTOMERS_MORE_REQUEST = 'CUSTOMERS_MORE_REQUEST'
export const CUSTOMERS_MORE_RECEIVE = 'CUSTOMERS_MORE_RECEIVE'

export const CUSTOMERS_FILTER_SET_SEARCH = 'CUSTOMERS_FILTER_SET_SEARCH'

export const CUSTOMERS_SELECT = 'CUSTOMERS_SELECT'
export const CUSTOMERS_DESELECT = 'CUSTOMERS_DESELECT'
export const CUSTOMERS_SELECT_ALL = 'CUSTOMERS_SELECT_ALL'
export const CUSTOMERS_DESELECT_ALL = 'CUSTOMERS_DESELECT_ALL'

// export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST'
// export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS'
// export const CUSTOMER_UPDATE_FAILURE = 'CUSTOMER_UPDATE_FAILURE'

// export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_SET_GROUP_SUCCESS = 'CUSTOMER_SET_GROUP_SUCCESS'
