export const STATUSES_REQUEST = 'STATUSES_REQUEST';
export const STATUSES_RECEIVE = 'STATUSES_RECEIVE';
export const STATUSES_FAILURE = 'STATUSES_FAILURE';

export const STATUSES_SELECT = 'STATUSES_SELECT';
export const STATUSES_DESELECT = 'STATUSES_DESELECT';

export const STATUS_UPDATE_REQUEST = 'STATUS_UPDATE_REQUEST';
export const STATUS_UPDATE_SUCCESS = 'STATUS_UPDATE_SUCCESS';
export const STATUS_UPDATE_FAILURE = 'STATUS_UPDATE_FAILURE';

export const STATUS_CREATE_SUCCESS = 'STATUS_CREATE_SUCCESS';
export const STATUS_DELETE_SUCCESS = 'STATUS_DELETE_SUCCESS';
