export const PRODUCT_RECEIVE = 'PRODUCT_RECEIVE'
export const SITEMAP_RECEIVE = 'SITEMAP_RECEIVE'
export const CATEGORIES_RECEIVE = 'CATEGORIES_RECEIVE'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE'
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_RECEIVE = 'CHECKOUT_RECEIVE'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const CART_REQUEST = 'CART_REQUEST'
export const CART_RECEIVE = 'CART_RECEIVE'
export const CART_FAILURE = 'CART_FAILURE'

export const CART_ITEM_ADD_REQUEST = 'CART_ITEM_ADD_REQUEST'
export const CART_ITEM_ADD_RECEIVE = 'CART_ITEM_ADD_RECEIVE'
export const CART_ITEM_ADD_FAILURE = 'CART_ITEM_ADD_FAILURE'

export const CART_ITEM_DELETE_REQUEST = 'CART_ITEM_DELETE_REQUEST'
export const CART_ITEM_DELETE_RECEIVE = 'CART_ITEM_DELETE_RECEIVE'
export const CART_ITEM_DELETE_FAILURE = 'CART_ITEM_DELETE_FAILURE'

export const CART_ITEM_UPDATE_REQUEST = 'CART_ITEM_UPDATE_REQUEST'
export const CART_ITEM_UPDATE_RECEIVE = 'CART_ITEM_UPDATE_RECEIVE'
export const CART_ITEM_UPDATE_FAILURE = 'CART_ITEM_UPDATE_FAILURE'

export const SHIPPING_METHODS_REQUEST = 'SHIPPING_METHODS_REQUEST'
export const SHIPPING_METHODS_RECEIVE = 'SHIPPING_METHODS_RECEIVE'
export const SHIPPING_METHODS_FAILURE = 'SHIPPING_METHODS_FAILURE'

export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST'
export const PAYMENT_METHODS_RECEIVE = 'PAYMENT_METHODS_RECEIVE'
export const PAYMENT_METHODS_FAILURE = 'PAYMENT_METHODS_FAILURE'

export const COUNTRIES_RECEIVE = 'COUNTRIES_RECEIVE'

export const PAGE_REQUEST = 'PAGE_REQUEST'
export const PAGE_RECEIVE = 'PAGE_RECEIVE'
export const PAGE_FAILURE = 'PAGE_FAILURE'
