export const THEMES_EXPORT_REQUEST = 'THEMES_EXPORT_REQUEST'
export const THEMES_EXPORT_RECEIVE = 'THEMES_EXPORT_RECEIVE'

export const THEMES_INSTALL_REQUEST = 'THEMES_INSTALL_REQUEST'
export const THEMES_INSTALL_RECEIVE = 'THEMES_INSTALL_RECEIVE'

export const SETTINGS_RECEIVE = 'SETTINGS_RECEIVE'
export const EMAIL_SETTINGS_RECEIVE = 'EMAIL_SETTINGS_RECEIVE'

export const EMAIL_TEMPLATE_REQUEST = 'EMAIL_TEMPLATE_REQUEST'
export const EMAIL_TEMPLATE_RECEIVE = 'EMAIL_TEMPLATE_RECEIVE'

export const SHIPPING_METHODS_REQUEST = 'SHIPPING_METHODS_REQUEST'
export const SHIPPING_METHODS_RECEIVE = 'SHIPPING_METHODS_RECEIVE'

export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST'
export const PAYMENT_METHODS_RECEIVE = 'PAYMENT_METHODS_RECEIVE'

export const SHIPPING_METHOD_REQUEST = 'SHIPPING_METHOD_REQUEST'
export const SHIPPING_METHOD_RECEIVE = 'SHIPPING_METHOD_RECEIVE'

export const PAYMENT_METHOD_REQUEST = 'PAYMENT_METHOD_REQUEST'
export const PAYMENT_METHOD_RECEIVE = 'PAYMENT_METHOD_RECEIVE'

export const CHECKOUT_FIELD_REQUEST = 'CHECKOUT_FIELD_REQUEST'
export const CHECKOUT_FIELD_RECEIVE = 'CHECKOUT_FIELD_RECEIVE'

export const CHECKOUT_FIELDS_REQUEST = 'CHECKOUT_FIELDS_REQUEST'
export const CHECKOUT_FIELDS_RECEIVE = 'CHECKOUT_FIELDS_RECEIVE'

export const PAGES_REQUEST = 'PAGES_REQUEST'
export const PAGES_RECEIVE = 'PAGES_RECEIVE'

export const PAGE_REQUEST = 'PAGE_REQUEST'
export const PAGE_RECEIVE = 'PAGE_RECEIVE'
