export const THEMES_EXPORT_REQUEST = 'THEMES_EXPORT_REQUEST'
export const THEMES_EXPORT_RECEIVE = 'THEMES_EXPORT_RECEIVE'

export const THEMES_INSTALL_REQUEST = 'THEMES_INSTALL_REQUEST'
export const THEMES_INSTALL_RECEIVE = 'THEMES_INSTALL_RECEIVE'

export const SETTINGS_RECEIVE = 'SETTINGS_RECEIVE'
export const EMAIL_SETTINGS_RECEIVE = 'EMAIL_SETTINGS_RECEIVE'

export const EMAIL_TEMPLATE_REQUEST = 'EMAIL_TEMPLATE_REQUEST'
export const EMAIL_TEMPLATE_RECEIVE = 'EMAIL_TEMPLATE_RECEIVE'
