export const THEMES_EXPORT_REQUEST = 'THEMES_EXPORT_REQUEST'
export const THEMES_EXPORT_RECEIVE = 'THEMES_EXPORT_RECEIVE'

export const THEMES_INSTALL_REQUEST = 'THEMES_INSTALL_REQUEST'
export const THEMES_INSTALL_RECEIVE = 'THEMES_INSTALL_RECEIVE'
