export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_RECEIVE = 'CATEGORIES_RECEIVE';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const CATEGORIES_SELECT = 'CATEGORIES_SELECT';
export const CATEGORIES_DESELECT = 'CATEGORIES_DESELECT';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAILURE = 'CATEGORY_UPDATE_FAILURE';

export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_MOVE_UPDOWN_SUCCESS = 'CATEGORY_MOVE_UPDOWN_SUCCESS';
export const CATEGORY_REPLACE_SUCCESS = 'CATEGORY_REPLACE_SUCCESS';

export const CATEGORY_IMAGE_UPLOAD_START = 'CATEGORY_IMAGE_UPLOAD_START';
export const CATEGORY_IMAGE_UPLOAD_END = 'CATEGORY_IMAGE_UPLOAD_END';
